name: Coverage

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.x
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install tox
      - name: Coverage
        run: tox -e coverage
